version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  backend:
    build: ./back
    env_file:
      - ./back/.env.docker
    ports:
      - 5500:5500

  frontend:
    build: ./front
    ports:
      - 4200:4200
    # env_file:
    #   - ./front/.env.docker
    environment:
      - NODE_ENV=production
    #   - backend_url=http://backend:5000
    depends_on:
      - backend
